#!/usr/bin/env python3
import itertools

import pyglet
from pyrr import Vector3

from psaux.world import World
from psaux.config import WIDTH, HEIGHT, MAX_FPS


class ParticleWindow(pyglet.window.Window):
    def __init__(self, *args, **kwargs):
        super().__init__(width=WIDTH, height=HEIGHT, resizable=True, *args, **kwargs)
        pyglet.gl.glClearColor(0.15, 0.1, 0.2, 1.0)
        pyglet.clock.schedule_interval(self.update, 1 / MAX_FPS)

        self.world = World()
        self.fps_display = pyglet.window.FPSDisplay(self)

        self.click_coord = None
        self.drag = False

    def on_draw(self):
        self.clear()
        self.world.draw()
        self.fps_display.draw()

    def update(self, delta_time: float):
        self.world.update(delta_time)

    def on_mouse_press(self, x: float, y: float, button: int, modifiers: int):
        self.click_coord = (x, y)
        if modifiers == 1:
            self.world.place_sun(x, y)

    def on_mouse_drag(
            self, x: float, y: float, dx: float, dy: float, buttons: int, modifiers: int
    ):
        """
        two modes:
        - left click spawns particle, which has velocity relative to movement
        - right click moves screen
        """
        if buttons == 1:
            self.drag = True
        else:
            for particle in self.world.particles:
                particle.position += Vector3([dx, dy, 0])

    def on_mouse_release(self, x: float, y: float, button: int, modifiers: int):
        if self.drag and modifiers == 0:
            start_x, start_y = self.click_coord
            movement_vector = Vector3([x - start_x, y - start_y, 0])
            delta_x, delta_y, _ = movement_vector

            self.world.spawn_planet(
                float(start_x), float(start_y), delta_x / 1e6, delta_y / 1e6
            )

        self.click_coord = None
        self.drag = False

    def on_mouse_scroll(self, x, y, scroll_x, scroll_y):
        self.world.time_warp_factor += scroll_x * 1e4


if __name__ == "__main__":
    window = ParticleWindow(caption="psaux")
    window.set_minimum_size(640, 480)
    pyglet.app.run()
