#!/usr/bin/env python3

import datetime
import logging

import pyglet

from psaux.window import ParticleWindow


if __name__ == "__main__":
    log_filename = '{}.log'.format(int(datetime.datetime.now().timestamp()))
    logging.basicConfig(filename=log_filename, level=logging.INFO)
    window = ParticleWindow()
    window.set_minimum_size(640, 480)
    logging.info("starting run")
    pyglet.app.run()
