#!/usr/bin/env python3

from argparse import ArgumentParser
import datetime
import logging
from pathlib import Path

import pyglet

from psaux.app import ParticleSimulator
from psaux.config import PsauxConfig


def psaux(args):
    if args.debug:
        log_folder = Path.cwd() / "logs"
        log_folder.mkdir(parents=True, exist_ok=True)
        log_filename = f'{log_folder}/{datetime.datetime.now().strftime("%Y-%b-%d %H:%M")}.log'
        logging.basicConfig(
            filename=log_filename,
            level=logging.DEBUG,
            format="%(created)f - %(levelname)s - %(message)s"
        )
    else:
        logging.basicConfig(level=logging.WARN)

    app = ParticleSimulator()
    app.set_minimum_size(640, 480)
    pyglet.app.run()


def main():
    parser = ArgumentParser()
    parser.add_argument("--debug", action="store_true")
    args = parser.parse_args()
    psaux(args)


if __name__ == "__main__":
    main()

