#!/usr/bin/env python3
"""
    Utility script to check velocities and positions of entities.
    Used for debugging.

    A bit primitive:
    - define log file
    - define rows and columns (to cover all entities)
"""

import sys

from matplotlib import pyplot as plt

from psaux.config import PsauxConfig

from scripts.logreader import get_data

WORLD_HEIGHT = PsauxConfig.height
WORLD_WIDTH = PsauxConfig.width


if len(sys.argv) == 2:
    filename = sys.argv[1]
else:
    filename = "../2020-Nov-30 17:43.log"

dataset = get_data(filename)

max_id = max([line[3] for line in dataset])
time_start = min([line[0] for line in dataset if line[3] == 1])
time_end = max([line[0] for line in dataset if line[3] == 1])

plots = []

for i in range(max_id):
    fig, axs = plt.subplots(1, 3)
    axs = axs.flatten()
    plots.append([fig, axs])

    time = [line[0] - time_start for line in dataset if line[3] == i + 1]
    position = [line[1] for line in dataset if line[3] == i + 1]
    velocity = [line[2] for line in dataset if line[3] == i + 1]
    print(f"{min(velocity)=}, {max(velocity)=}")  # todo: remove
    forces = [line[4] for line in dataset if line[3] == i + 1]

    fig.suptitle(i + 1)

    axs[0].set_title("position")
    axs[0].plot(
        [direction[0] for direction in position],
        [direction[1] for direction in position],
    )
    axs[0].set_xlim(-0.5 * WORLD_WIDTH, 1.5 * WORLD_WIDTH)
    axs[0].set_ylim(-0.5 * WORLD_HEIGHT, 1.5 * WORLD_HEIGHT)

    axs[1].set_title("velocity")
    for j, char in enumerate(["x", "y"]):
        axs[1].plot(time, [direction[j] for direction in velocity], label=char)
        axs[1].set_xlim(0, time_end - time_start)
    axs[1].set_ylim(-1e-2, 1e-2)

    axs[2].set_title("force")
    axs[2].plot(time, forces)
    axs[2].set_yscale('log')
    axs[2].set_ylim(top=1e-3)
    axs[2].set_xlim(0, time_end - time_start)

for plot in plots:
    plot[0].show()
