on: push
name: on push
jobs:
  test:
    name: pytest
    runs-on: macos-11
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: pytest
      run: pytest
